name: Github Actions First Demo
on: push
jobs: 
    third-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: node -v
        - run: npm -v
        - run: node index.js
        - run: npm install
        - run: npm run lint

